# Jacobi Method

From: https://en.wikipedia.org/wiki/Jacobi_method :
#### Jacobi Method
In numerical linear algebra, the Jacobi method is an iterative algorithm for determining the solutions of a diagonally dominant system of linear equations.
<br>
<br>
#### Convergence
A sufficient (but not necessary) condition for the method to converge is that the matrix A is strictly or irreducibly diagonally dominant.

<br>
<br>

#### Description
Let
:$A\mathbf x = \mathbf b$

be a square system of $n$ linear equations, where:

$A=\begin{bmatrix} a_{11} & a_{12} & \cdots & a_{1n} \\ a_{21} & a_{22} & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\a_{n1} & a_{n2} & \cdots & a_{nn} \end{bmatrix}, \qquad  \mathbf{x} = \begin{bmatrix} x_{1} \\ x_2 \\ \vdots \\ x_n \end{bmatrix} , \qquad  \mathbf{b} = \begin{bmatrix} b_{1} \\ b_2 \\ \vdots \\ b_n \end{bmatrix}.$

Then ''A'' can be decomposed into a diagonal matrix $D$, and the remainder $R$:

:$A=D+R \qquad \text{where} \qquad D = \begin{bmatrix} a_{11} & 0 & \cdots & 0 \\ 0 & a_{22} & \cdots & 0 \\ \vdots & \vdots & \ddots & \vdots \\0 & 0 & \cdots & a_{nn} \end{bmatrix} \text{ and } R = \begin{bmatrix} 0 & a_{12} & \cdots & a_{1n} \\ a_{21} & 0 & \cdots & a_{2n} \\ \vdots & \vdots & \ddots & \vdots \\ a_{n1} & a_{n2} & \cdots & 0 \end{bmatrix}. $

The solution is then obtained iteratively via
:$ \mathbf{x}^{(k+1)} = D^{-1} (\mathbf{b} - R \mathbf{x}^{(k)}), $

where $\mathbf{x}^{(k)}$ is the $k$th approximation or iteration of $\mathbf{x}$ and $\mathbf{x}^{(k+1)}$ is the next or $k$ + 1 iteration of $\mathbf{x}$.

$$x^{(k+1)}=D^{-1}(b - Rx^{(k)})$$
#### Equivalently:
##### (In the following Code following equations have been used):
$$x^{(k+1)}= Tx^{(k)} + C $$ 
$$T=-D^{-1}R $$
$$C = D^{-1}b $$

#### Stop Condition:
$$ \lVert X^{(k+1)} - X^{(k)} \rVert_2 \le 10^{-4}$$


In [1]:
import numpy as np

In [2]:
def jacobi(A,b,initial_guess):
    #Extracting Diagonal elements from input matrix A:
    Diagnal = np.diag(A)
    D = np.diagflat(Diagnal)
    
    #Calculating Invese of D:
    D_inv = np.linalg.inv(D)
    
    #Calculating R:
    R = A - D
    
    #Symbol of matrix multiplication in numpy is @
    T = -D_inv@R
    C = D_inv@b
    x = initial_guess

    while(1):
        x_old = x
        x = T@x + C
        x_new = x
        #using norm2:
        if np.linalg.norm(x_new-x_old) <= 10**(-4):
            break
    return x

In [3]:
A = np.matrix([[2.0,1.0],
               [5.0,7.0]])

b = np.matrix([[11.0],[13.0]])

initialGuess = np.matrix([[1.0],[1.0]])

sol = jacobi(A,b,initialGuess)

print ('A:')
print(A)

print ('\nb:')
print(b)

print('\nSolution:')
print(sol)

A:
[[2. 1.]
 [5. 7.]]

b:
[[11.]
 [13.]]

Solution:
[[ 7.11103743]
 [-3.22217131]]
